### ISSUE TITLE
Npgsql.CrateDb needs to be strongly-named assembly.

### ISSUE THREAD

**Issue by biglobe** [crate/crate-npgsql#12]
Hi, I am using Npgsql.CrateDb that was loaded from Nuget. In my scenario, ASP.net complains that the assembly needs to be strongly-name.

It seem Npgsql is strongly named, but not the Crate version of Npgsql. Someone might want to post a signed one to Nuget?

![image](https://user-images.githubusercontent.com/4609085/46472405-a26e4380-c80f-11e8-8ad1-cc7ec2977c79.png)

**Comment by apircher** [comment]
Hi @biglobe, we are just finishing our GAC installer which contains a strongly named version of the Crate.io fork. So a new Nuget package with a signed version of the Crate.io fork should be available pretty soon.

**Comment by monanllc** [comment]
Will there be any conflicts if both original npgsql and cratedb are in GAC?

**Comment by apircher** [comment]
Hi @monanllc, theoretically not. The official npgsql and the Crate.io fork each have their own strong names so they should be able to live side by side in the GAC. The entry for the Npgsql Data Provider in machine.config determines, which assembly will be used.

But there should be no problem using the Crate.io fork to access PostgreSQL and CrateDB.

**Comment by monanllc** [comment]
@apircher Thanks for clarification. May I ask when did you fork the npgsql (pre-4.x vs post-4.x)?

**Comment by apircher** [comment]
@monanllc We forked pre-4.x but we rebase on a regular basis. Currently we are on the state of the beginning of August - so it's clearly post-4x.

**Comment by monanllc** [comment]
@apircher thanks for the info.
