### ISSUE TITLE
Version specifications missing

### ISSUE THREAD

**Issue by PhilippJust** [crate/crate-npgsql#42]
###  Documentation feedback

 
- Page title: Connect to CrateDB
- Page URL: https://crate.io/docs/npgsql/en/latest/connect.rst
- Source: https://github.com/crate/crate-npgsql/blob/master/docs/connect.html

---

I tried to use the Npsql client for cratedb as described in the docs with a minimum example. I have a three-node-cluster running with a docker image on localhost.

Here is the very simple console app

`.csproj` file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="4.1.3.1" />
    <PackageReference Include="Npgsql.CrateDb" Version="1.2.3" />
  </ItemGroup>
</Project>
```

Executed file with the code copy-pasted from the docs
```csharp
using Npgsql;
using Npgsql.CrateDb;

namespace CrateHelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            NpgsqlDatabaseInfo.RegisterFactory(new CrateDbDatabaseInfoFactory());
            var connString = "Host=127.0.0.1;Username=crate;SSL Mode=Prefer";

            using (var conn = new NpgsqlConnection(connString))
            {
                conn.Open();
            }
        }
    }
}
```

However `conn.Open()` always throws an exception
`An unhandled exception of type 'System.MissingMethodException' occurred in System.Private.CoreLib.dll: 'Method not found: 'Void Npgsql.NpgsqlDatabaseInfo..ctor()'.'`

I only got it running when downgrading Npgsql to version 4.0.10.
This should be written somewhere as it is really frustrating to not get a hello world running :)

**Comment by norosa** [comment]
this was fixed a while ago
